# This is a basic workflow to help you get started with Actions

name: Convert

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: exec_gpt2_convert_env
      - run: cd ./examples/rinna-gpt2-predict/src/
      - name: Install packages
        run: conda install --name exec_gpt2_convert_env --file exec_env.yml
      - name: Convert
        run: python convert_onnx.ipynb