# This is a basic workflow to help you get started with Actions

name: Convert

# Controls when the workflow will run
on:
  push:
    branches: [ convert-and-deploy-from-ga ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: exec_gpt2_convert_env
          environment-file: examples/rinna-gpt2-predict/src/exec_env.yml
      - name: Convert
        run: cd ./examples/rinna-gpt2-predict/src/ && /usr/share/miniconda/envs/exec_gpt2_convert_env/bin/python convert_model.py --credential ${{ secrets.AZURE_CREDENTIALS }}