name: MLOps-CICD

on:
  push:
    branches: [ gh-actions ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install Azure ML CLI 2.0
        run: az extension add -n ml -y
      - name: Check Azure Subscription
        run: az account show -o table
      - name: Default Azure ML Workspace
        run: az configure --defaults group="mlops" workspace="azureml-mlops"
      - name: Train Model
        run: az ml job create --file ./examples/rinna-gpt2-train/cli/rinna_trainer_job.yml --stream
